name: CD

on:
  push:
    branches: [main]

permissions:
  id-token: write

env:
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  TF_VAR_ec2_public_key: ${{ secrets.EC2_PUBLIC_KEY }}

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    outputs:
      ecr_repo_url: ${{ steps.tf-outputs.outputs.ecr_repo_url }}
      db_host: ${{ steps.tf-outputs.outputs.db_host }}
      ec2_public_ip: ${{ steps.tf-outputs.outputs.ec2_public_ip }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: us-east-2
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: GHASession

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=./infra init

      - name: Terraform Plan
        run: terraform -chdir=./infra plan -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=./infra apply -auto-approve tfplan

      - name: Get Outputs
        id: tf-outputs
        run: |
          ecr_repo_url=$(terraform -chdir=./infra output -raw ecr_repo_url)
          echo "ecr_repo_url=$ecr_repo_url" >> $GITHUB_OUTPUT

          db_host=$(terraform -chdir=./infra output -raw db_host)
          echo "db_host=$db_host" >> $GITHUB_OUTPUT

          ec2_public_ip=$(terraform -chdir=./infra output -raw ec2_public_ip)
          echo "ec2_public_ip=$ec2_public_ip" >> $GITHUB_OUTPUT

  build-and-push-image:
    needs: deploy-infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::040865381987:role/gha_role
          role-session-name: GHASession

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          labels: service=code
          tags: |
            ${{ needs.deploy-infra.outputs.ecr_repo_url }}:latest
            ${{ needs.deploy-infra.outputs.ecr_repo_url }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-app:
    needs: [deploy-infra, build-and-push-image]
    runs-on: ubuntu-latest

    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::040865381987:role/gha_role
          role-session-name: GHASession

      - name: Create env file
        run: |
          echo "DATABASE_URL=postgresql://breadshelf_user:${{ secrets.DB_PASSWORD }}@${{ needs.deploy-infra.outputs.db_host }}/breadshelf_production" >> .env
          echo "RAILS_ENV=production" >> .env

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Write SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy command
        run: bundle exec kamal setup --skip-push
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SERVER_IP_ADDRESS: ${{ needs.deploy-infra.outputs.ec2_public_ip }}
