name: CD

on:
  push:
    branches: [main]

permissions:
  id-token: write

env:
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    outputs:
      ecr_repo_url: ${{ steps.tf-outputs.outputs.ecr_repo_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: us-east-2
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: GHASession

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=./infra init

      - name: Terraform Plan
        run: terraform -chdir=./infra plan -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=./infra apply -auto-approve tfplan

      - name: Get Outputs
        id: tf-outputs
        run: |
          ecr_repo_url=$(terraform -chdir=./infra output -raw ecr_repo_url)
          echo "ecr_repo_url=$ecr_repo_url" >> $GITHUB_OUTPUT

  build-and-push-image:
    needs: deploy-infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::040865381987:role/gha_role
          role-session-name: GHASession

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ needs.deploy-infra.outputs.ecr_repo_url }}:latest
            ${{ needs.deploy-infra.outputs.ecr_repo_url }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
